name: Deploy ECS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install --upgrade pip
          pip3 install awscli

      - name: Create ECS Cluster
        run: |
          aws ecs create-cluster --cluster-name my-cluster --capacity-providers FARGATE --region us-east-2
